import "./globals.css";
import type { Metadata } from "next";
import { Inter, Kreon } from "next/font/google";
import ReduxProvider from ".";

const kreon = Kreon({ subsets: ["latin"] });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en">
        <body className={kreon.className}><ReduxProvider>{children}</ReduxProvider></body>
      </html>
  );
}
